# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Workflow de Integração Contínua.

on:
  pull_request:
    branches: [ "main" ]

jobs:
  teste:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 #clone do projeto na Maquina Ubuntu
    - name: Use Node.js # nome da action
      uses: actions/setup-node@v3 # seta o node na verção
      with:
        node-version: 20.
    - run: npm install # Instala as dependencias no projeto
    - run: npm test
